---
- name: apache 2.4 settings
  hosts: all
  remote_user: ec2-user
  roles:
    - role: apache24
    - role: php73
  vars:
    ansible_ssh_private_key_file: "/Users/yusuke.ono/Develop/Aws/credentials/20200527-devepment.pem"
