---
- name: apache 2.4 / php 7.3 settings
  hosts: all
  remote_user: ec2-user
  roles:
    - role: initial
    - role: codedeployagent
    - role: apache24
    - role: php73
    - role: goss
    - role: git
    - role: apps
