---
# tasks file for php73
- name: Hello World!
  debug:
    msg: "Hello World! php73"

- name: php 7.3 enable
  command: "amazon-linux-extras enable php7.3"
  become: yes

- name: php modules install from amazon-linux-extras
  yum:
    name: "{{ modules }}"
  vars:
    modules:
      - php
      - php-mbstring
      - php-gd
      - php-pdo
      - php-mysqlnd
      - php-pear
      - php-devel
  become: yes

- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: composer install
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  become: yes

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  become: yes

- name: make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  become: yes

- name: service restart
  service:
    name: httpd
    state: restarted
  become: yes
