---
# tasks file for git
- name: git yum install
  yum:
    name: git
    state: present
  become: yes

- name: Ensure GitHub deploy key is present on the server.
  copy:
    src: ~/.ssh/id_ed25519-github-deploy-key
    dest: /home/ec2-user/.ssh
    mode: "0600"
    owner: ec2-user
    group: ec2-user

- name: Evaluating the authentication agent & adding the key...
  shell: |
    eval "$(ssh-agent)"
    ssh-add /home/ec2-user/.ssh/id_ed25519-github-deploy-key
